export const properties = {
  equivalent: 0,
  quantity: 0,
  gross_weight: 0,
  net_weight: 0,
  energy: 0,
  proteins: 0,
  lipids: 0,
  carbohydrates: 0,
  saturated_fa: 0,
  monounsaturated_fa: 0,
  polyunsaturated_fa: 0,
  cholesterol: 0,
  sugar: 0,
  fiber: 0,
  vitamin_a: 0,
  ascorbic_acid: 0,
  folic_acid: 0,
  calcium: 0,
  iron: 0,
  potassium: 0,
  sodium: 0,
  phosphorus: 0,
  ethanol: 0,
  ig: 0,
  glycemic_load: 0,
}